myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index),
    path('products', views.products),
    path('products/<str:contract_address>/<str:contract_name>/<int:contract_num_sales>', views.product_details, name='product_details'),
    path('contract/<str:contract_address>', views.contract, name='contract'), 
    path('address/', views.address_transactions, name='address'), 
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('', include('myapp.urls')),
]

myapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self) -> str:
        return self.name

myapp/views.py
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product
import requests

CO2_PER_TRANSACTION = 40
CO2_FOR_MINTING = 18

def index(request):

    # Get assets for a certain address
    if request.method == 'POST':
        address = request.POST.get('search')
        total_sales = 0
        
        url = f"https://testnets-api.opensea.io/api/v1/assets?owner={address}&order_direction=desc&offset=0&limit=20&include_orders=false"

        response = requests.get(url).json()

        assets_list = response['assets']
        for asset in assets_list:
            sales = asset['num_sales']
            total_sales += int(sales)

        sales_carbon = total_sales * CO2_PER_TRANSACTION

        context = {
            "search_address": address,
            "total_assets": len(response['assets']),
            "total_sales": total_sales,
            "sales_carbon": sales_carbon,
            "minting_carbon": CO2_FOR_MINTING,
            "total_carbon": CO2_FOR_MINTING + sales_carbon
        }

        return render(request, 'myapp/address_consumption.html', context)

    else:
        url_get_assets = "https://testnets-api.opensea.io/api/v1/assets?order_by=sale_count&order_direction=desc&offset=0&limit=50&include_orders=true"

        response = requests.get(url_get_assets).json()

        return render(request, 'myapp/index.html', {"response": response['assets']})


def products(request):
    products = Product.objects.all()

    context = {"products": products}

    return render(request, 'myapp/index.html', context)


def product_details(request, contract_address, contract_name, contract_num_sales):
    
    print(f"contract address is : {contract_address}")

    sales = contract_num_sales * CO2_PER_TRANSACTION

    context = {
        "name": contract_name,
        "minting": CO2_FOR_MINTING,
        "sales_count": contract_num_sales,
        "total_sales": sales,
        "total": (contract_num_sales * CO2_PER_TRANSACTION) + CO2_FOR_MINTING

    }

    return render(request, 'myapp/detail.html', context)


def contract(request, contract_address):

    url = f"https://testnets-api.opensea.io/api/v1/asset_contract/{contract_address}"

    response = requests.get(url).json()

    context = {
        "contract": response["collection"]
    }

    return render(request, 'myapp/contracts.html', context)


def asset_events(request, account_address):

    url = f"https://testnets-api.opensea.io/api/v1/events?account_address={account_address}&only_opensea=false&limit=20"

    headers = {"Accept": "application/json"}

    response = requests.get(url, headers=headers)

    context = {
        "assets": response
    }

    return render(request, 'myapp/user_asset_events.html', context)


def address_transactions(request):
    print("This address has many transactions")

myapp/templates/myapp/address_consumption.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Emissions by Address</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
    <div class="container my-12 mx-auto px-4 md:px-12">
        <div class="h-56 grid grid-cols-3 gap-4 content-center" >
            <span class="text-gray-500 font-semibold text-xl">Address: {{ search_address }}</span>
            <span class="text-gray-500 font-semibold text-xl">Address: {{ search_address }}</span>
        </div>
        <div class="max-w-full mx-4 py-6 sm:mx-auto sm:px-6 lg:px-8">
            <div class="sm:flex sm:space-x-4">
                <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow mb-4 w-full sm:w-1/3 sm:my-8">
                    <div class="bg-white p-5">
                        <div class="sm:flex sm:items-start">
                            <div class="text-center sm:mt-0 sm:ml-2 sm:text-left">
                                <h3 class="text-m leading-6 font-medium text-gray-700">Number of assets available</h3>
                                <p class="text-3xl font-bold text-black">{{ total_assets }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow mb-4 w-full sm:w-1/3 sm:my-8">
                    <div class="bg-white p-5">
                        <div class="sm:flex sm:items-start">
                            <div class="text-center sm:mt-0 sm:ml-2 sm:text-left">
                                <h3 class="text-m leading-6 font-medium text-gray-700">Number of Sales</h3>
                                <p class="text-3xl font-bold text-black">{{ total_sales }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow mb-4 w-full sm:w-1/3 sm:my-8">
                    <div class="bg-white p-5">
                        <div class="sm:flex sm:items-start">
                            <div class="text-center sm:mt-0 sm:ml-2 sm:text-left">
                                <h3 class="text-m leading-6 font-medium text-gray-700">Approximate total CO2 Cost</h3>
                                <p class="text-3xl font-bold text-black">{{total_carbon}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</body>
</html>

myapp/templates/myapp/contracts.html
{{ contract }}

myapp/templates/myapp/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>NFTs WATCHER</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    <header class="flex content-center items-center justify-between leading-tight p-4 md:p-6">
        <p class="ml-2 text-xl">
            CO2 Emissions by: {{ name }}
        </p>
    </header>
    
    <div class="w-50 text-sm font-medium text-gray-900 bg-white rounded-m border border-gray-400 dark:bg-gray-600 dark:border-gray-600 dark:text-white">
        <canvas id="myChart" class="w-2"></canvas>
    </div>
    
    <footer class="flex items-center justify-between leading-none p-4 md:p-6">
        <p class="ml-2 text-xl">
            Total Carbon Cost: {{ total }}
        </p>
    </footer>
</body>
</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>
<script>
const ctx = document.getElementById('myChart').getContext('2d');
const myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Minting', 'Sales', 'Total'],
        datasets: [{
            label: 'Total CO2eq Emissions (kgCO2)',
            data: [{{minting}}, {{total_sales}}, {{ total }},],
            backgroundColor: [
                'rgba(255, 99, 132)',
                'rgba(54, 162, 235',
                'rgba(255, 206, 86',
            ],
            borderColor: [
                'rgba(255, 99, 132, 0.5)',
                'rgba(54, 162, 235, 0.5)',
                'rgba(255, 206, 86, 0.5)',
            ],
            borderWidth: 10
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>

myapp/templates/myapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NFTs WATCHER</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    <div class="container my-12 mx-auto px-4 md:px-12">
        <div class="h-56 grid grid-cols-3 gap-4 content-center" >
            <span class="text-gray-500 font-semibold text-xl">Track the Carbon footprint of popular NFTs</span>
        </div>

        <div class="relative text-gray-600 mb-5">
            <form action="" method="POST">
                {% csrf_token %}
                <input type="search" name="search" placeholder="Enter account Address" class="bg-white h-10 px-5 pr-10 rounded-full text-m ">
                <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                <svg class="h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
                    <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"/>
                </svg>
                </button>
            </form>
          </div>

        <div class="flex flex-wrap -mx-1 lg:-mx-4">
        {% for row in response%}
            <div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">

                <article class="overflow-hidden rounded-lg shadow-lg hover:shadow-2xl">

                    <a href="{% url 'myapp:product_details' contract_address=row.asset_contract.address contract_name=row.asset_contract.name contract_num_sales=row.num_sales  %}">
                        {% if  row.asset_contract.image_url%}
                        <img alt="NFT Image" class="block h-auto w-full nft_image" src="{{row.asset_contract.image_url}}">
                        {% else %}
                        <img alt="Not Fund" class="block h-auto w-full nft_image" src="{% static 'myapp/images/not_found.jpg' %}">
                        {% endif %}
                    </a>
    
                    <header class="flex items-center justify-between leading-tight p-2 md:p-4">
                        <h1 class="text-lg">
                            <a class="no-underline hover:underline text-black" href="#">
                                Contract Name: {{ row.asset_contract.name }}
                            </a>
                        </h1>
                        <p class="text-grey-darker text-sm">
                            ID: {{ row.id }}
                        </p>
                        
                    </header>
                    <footer class="flex items-center justify-between leading-none p-2 md:p-4">
                        <a class="flex items-center no-underline hover:underline text-black" href="#">
                            <p class="ml-2 text-sm">
                                Total Sales: {{ row.num_sales }}
                            </p>
                            <p class="ml-2 text-sm">
                                Created on: {{ row.asset_contract.created_date }}
                            </p>
                        </a>
                    </footer>
    
                    <footer class="flex items-center justify-between leading-none p-2 md:p-4">
                        <p class="text-sm">
                            {{ row.owner.address }}
                        </p> 
                    </footer>
    
                </article>
    
            </div>

        {% endfor %}

        </div>
    </div>

</body>

</html>

myapp/templates/myapp/user_asset_events.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Asset Events</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    <h1>User asset events</h1>
    {% for asset in assets %}
        {{asset}}
    {% endfor %}
    
</body>
</html>